# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    my_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

my_robot_controller:
  ros__parameters:
    joints:
      - base_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_link4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity